### ISSUE TITLE
Initial connection error [Windows]

### ISSUE THREAD

**Issue by DikozImpact** [KaringX/karing#571]
The first time you connect after restarting the system, an error occurs. It appears only once, and it does not occur when reconnecting 

launch process karingservice.exe failed: process exit:0:[31mERROR[0m[0016]  export.go:47 : start service: start inbound/tun[tun_in]: configure tun interface: Cannot create a file when that file already exists.

![Image](https://github.com/user-attachments/assets/358fd1c0-35c0-44be-b668-7d16d65708ba)

**Comment by dKenGuru** [comment]
You already have a TUN in system. Check network available connections.

**Comment by GooRingX** [comment]
try https://github.com/KaringX/karing/releases/tag/v1.1.0.562

**Comment by DikozImpact** [comment]
1.1.0.565
launch process karingservice.exe failed: process exit:0:[31mERROR[0m[0015]  export.go:47 : start service: start inbound/tun[tun_in]: configure tun interface: create: wintun : Failed to setup adapter (problem code: 0x1F, ntstatus: 0xC0000035): Невозможно создать файл, так как он уже существует. (Code 0x000000B7): Cannot create a file when that file already exists.


![Image](https://github.com/user-attachments/assets/ac6cfbf6-d0cc-465a-aaa2-a9528639cf5c)

The first days after the update was fine, today this error appeared on the first startup, after reconnecting it disappeared.

**Comment by GooRingX** [comment]
> 1.1.0.565 launch process karingservice.exe failed: process exit:0:�[31mERROR�[0m[0015] export.go:47 : start service: start inbound/tun[tun_in]: configure tun interface: create: wintun : Failed to setup adapter (problem code: 0x1F, ntstatus: 0xC0000035): Невозможно создать файл, так как он уже существует. (Code 0x000000B7): Cannot create a file when that file already exists.
> 
> ![Image](https://github.com/user-attachments/assets/ac6cfbf6-d0cc-465a-aaa2-a9528639cf5c)
> 
> The first days after the update was fine, today this error appeared on the first startup, after reconnecting it disappeared.

Open cmd with administrator privileges, enter dism /online /get-drivers /format:table > c:\drivers.txt, check if there is a wintun driver in it? Supplement the generated file content

**Comment by GooRingX** [comment]
Download the following wintun_amd64.zip, unzip it, and right-click wintun.inf to install the wintun driver
[wintun_amd64.zip](https://github.com/user-attachments/files/18900858/wintun_amd64.zip)

**Comment by GooRingX** [comment]
> Download the following wintun_amd64.zip, unzip it, and right-click wintun.inf to install the wintun driver [wintun_amd64.zip](https://github.com/user-attachments/files/18900858/wintun_amd64.zip)

Before installation, check whether there is a driver starting with wintun in the C:\Windows\System32\DriverStore\FileRepository\ directory, such as wintun.inf_amd64_8ed20477a29aa8f7

**Comment by DikozImpact** [comment]
> Before installation, check whether there is a driver starting with wintun in the C:\Windows\System32\DriverStore\FileRepository\ directory, such as wintun.inf_amd64_8ed20477a29aa8f7

![Image](https://github.com/user-attachments/assets/e802267d-5f35-405b-8c6a-4b9466a86ba6)

I already have it

**Comment by DikozImpact** [comment]
![Image](https://github.com/user-attachments/assets/d54078e8-aeec-4e94-bdc7-7add807cf571)

Same first startup error on latest pre-release

**Comment by dKenGuru** [comment]
Clear profile folders in regedit

**Comment by GooRingX** [comment]
Try deleting all registry entries containing karing or tun under HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\NetworkList\Profiles

**Comment by GooRingX** [comment]
Try to see if the flclash tun mode can start normally

**Comment by DmitriyFrogo** [comment]
Can reproduce this issue after cleaning registry + deleting all adapters and drivers in device manager
When you enable Karing, in device manager we can see error

```
This device is not working properly because Windows cannot load the drivers required for this device (Code 31).
An object ID was not found in the file 
```


![Image](https://github.com/user-attachments/assets/1551e645-087c-4c0c-ad7f-6b613e5c149b)

**Comment by dKenGuru** [comment]
May be disable UserChoice Protection Driver (UCPD) or UAC in low mode can help

**Comment by DmitriyFrogo** [comment]
How I fixed this
1. Close Karing (check Task Manager twice)
2. Delete all Karing TUN profiles in registry (HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\NetworkList\Profiles and HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\NetworkList\Signatures\Unmanaged)
3. Go to Device Manager, enable "show hidden devices", force delete Karing TUN
4. Download DriverStoreExplorer, find wintun.inf, check it, check "Force Delete", click Delete
5. Restart PC

**Comment by DikozImpact** [comment]
![Image](https://github.com/user-attachments/assets/0eb72cb8-5c3a-46f9-a23e-1c4d30ffc5f5)
The error still appears on newer versions

**Comment by GooRingX** [comment]
Try the suggestions above. This problem is not necessarily a karing bug.

**Comment by DikozImpact** [comment]
Tried the suggestion above, didn't help. Still the same error at the first startup :(

**Comment by dKenGuru** [comment]
Need a screenshot of full process list at background.

**Comment by GooRingX** [comment]
Clear C:\Windows\INF\setupapi.dev.log and connect. If a problem occurs, upload the C:\Windows\INF\setupapi.dev.log file.

**Comment by WahaWaher** [comment]
> Clear C:\Windows\INF\setupapi.dev.log and connect. If a problem occurs, upload the C:\Windows\INF\setupapi.dev.log file.

[setupapi.dev.log](https://github.com/user-attachments/files/19644414/setupapi.dev.log)

I have done everything that is indicated in this topic, but the problem still exists.

![Image](https://github.com/user-attachments/assets/a62429c6-fa3a-4575-9357-ac8e68df97f9)

**Comment by GooRingX** [comment]
> > Clear C:\Windows\INF\setupapi.dev.log and connect. If a problem occurs, upload the C:\Windows\INF\setupapi.dev.log file.
> 
> [setupapi.dev.log](https://github.com/user-attachments/files/19644414/setupapi.dev.log)
> 
> I have done everything that is indicated in this topic, but the problem still exists.
> 
> ![Image](https://github.com/user-attachments/assets/a62429c6-fa3a-4575-9357-ac8e68df97f9)


Try:
1. Export the list of drivers in the table form to a text file using the command:
dism /online /get-drivers /format:table > c:\drivers.txt

2. Find wintun or wireguard from the list, and note the "Published Name", oemNN.inf

3. Remove the driver using the command:
  pnputil.exe /d oemNN.inf

**Comment by GooRingX** [comment]
try https://github.com/KaringX/karing/releases/tag/v1.1.3.702

**Comment by taoqixfz** [comment]
试了一下这样可以解决![Image](https://github.com/user-attachments/assets/aa5444d3-d973-4363-84a3-107de04adb0f)

**Comment by taoqixfz** [comment]
![Image](https://github.com/user-attachments/assets/52877920-a1d7-4faa-923f-831e36db3a75)
![Image](https://github.com/user-attachments/assets/1b537305-dbe6-4376-ae4b-0e8f6f937885)
![Image](https://github.com/user-attachments/assets/d7d6c9bf-a0cd-42f2-9318-5f310bcd6d24)
重启电脑还是会经常性出现

**Comment by GooRingX** [comment]
> ![Image](https://github.com/user-attachments/assets/d7d6c9bf-a0cd-42f2-9318-5f310bcd6d24) ![Image](https://github.com/user-attachments/assets/1b537305-dbe6-4376-ae4b-0e8f6f937885) 重启电脑还是会经常概率性的出现

Export the list of drivers in the table form to a text file using the command:
dism /online /get-drivers /format:table > c:\drivers.txt

Find wintun or wireguard from the list, and note the "Published Name", oemNN.inf

Remove the driver using the command:
pnputil.exe /d oemNN.inf

**Comment by taoqixfz** [comment]
> > ![Image](https://github.com/user-attachments/assets/d7d6c9bf-a0cd-42f2-9318-5f310bcd6d24) ![Image](https://private-user-images.githubusercontent.com/5214282/446321045-1b537305-dbe6-4376-ae4b-0e8f6f937885.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDgxNDEyOTQsIm5iZiI6MTc0ODE0MDk5NCwicGF0aCI6Ii81MjE0MjgyLzQ0NjMyMTA0NS0xYjUzNzMwNS1kYmU2LTQzNzYtYWU0Yi0wZThmNmY5Mzc4ODUuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDUyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA1MjVUMDI0MzE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDk3YzA4N2Y4NjhhMTUzNjNhYWI5MjRkZWMyNDU2YTU2MmM0NDQwYzNkNWEzMTE3YzQ4ODZhZjVjZmRhMzhhOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.SOLz5OU8FEEXnH9XJEaG5rEKBjHT_VP1KYo0IXDrudY) 重启电脑还是会经常概率性的出现
> 
> Export the list of drivers in the table form to a text file using the command: dism /online /get-drivers /format:table > c:\drivers.txt
> 
> Find wintun or wireguard from the list, 和 note the "Published Name", oemNN.inf
> 
> Remove the driver using the command: pnputil.exe /d oemNN.inf

经测试删不删oem23.inf都不影响软件启动故障，我在任务计划程序里面运行、结束测试依旧有故障

**Comment by GooRingX** [comment]
> > > ![Image](https://github.com/user-attachments/assets/d7d6c9bf-a0cd-42f2-9318-5f310bcd6d24) ![Image](https://private-user-images.githubusercontent.com/5214282/446321045-1b537305-dbe6-4376-ae4b-0e8f6f937885.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDgxNDEyOTQsIm5iZiI6MTc0ODE0MDk5NCwicGF0aCI6Ii81MjE0MjgyLzQ0NjMyMTA0NS0xYjUzNzMwNS1kYmU2LTQzNzYtYWU0Yi0wZThmNmY5Mzc4ODUuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDUyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA1MjVUMDI0MzE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDk3YzA4N2Y4NjhhMTUzNjNhYWI5MjRkZWMyNDU2YTU2MmM0NDQwYzNkNWEzMTE3YzQ4ODZhZjVjZmRhMzhhOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.SOLz5OU8FEEXnH9XJEaG5rEKBjHT_VP1KYo0IXDrudY) 重启电脑还是会经常概率性的出现
> > 
> > 
> > Export the list of drivers in the table form to a text file using the command: dism /online /get-drivers /format:table > c:\drivers.txt
> > Find wintun or wireguard from the list, 和 note the "Published Name", oemNN.inf
> > Remove the driver using the command: pnputil.exe /d oemNN.inf
> 
> 经测试删不删oem23.inf都不影响软件启动故障，我在任务计划程序里面，运行、结束多次测试，测试依旧故障。

删除其他代理软件,重启设备再试试

**Comment by LittleOwlie** [comment]
I have been having the same issue for as long as I can remember. Often the previous Karing connection instance gets stuck and refuses to connect after the computer reboot (or rarely after Karing is reconnected), however, it always connects without issues the second time after I click 'Ok' on the error box and attempt to manually reconnect Karing again.
If the issue is unavoidable due to how Windows is designed, perhaps there should be an option to make Karing automatically attempt to reconnect after it detects such an error occurring?

**Comment by GooRingX** [comment]
try sing-box sfm

**Comment by GooRingX** [comment]
tun is a function implemented by wintun, at the driver level, and karing cannot fix/modify this function.

**Comment by kikuok** [comment]
I have also been experiencing this error for a long time. Please fix it.
